# Generated by Django 3.2.6 on 2021-09-15 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0003_alter_subject_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='register',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
